query GetEvent($id: String!) {
  event(id: $id) {
    id
    title
    description
    startTime
    endTime
    location
    status
    isPublic
    categoryId
    category {
      id
      name
      description
    }
    createdBy {
      id
      name
      username
      avatar {
        id
        secureUrl
      }
    }
    organizers {
      id
      role
      addedAt
      user {
        id
        name
        username
        avatar {
          id
          secureUrl
        }
      }
    }
    eventMedia {
      id
      secureUrl
      format
      resourceType
    }
    boardId
    createdAt
    updatedAt
  }
}
