query FeedPosts($after: String, $limit: Int) {
  feedPosts(after: $after, limit: $limit) {
    items {
      id
      textContent
      createdAt
      _count {
        replies
      }
      author {
        id
        username
        name
        avatar {
          secureUrl
          resourceType
        }
      }
      postMedia {
        id
        secureUrl
        resourceType
        format
        duration
      }
    }
    pageInfo {
      # startCursor
      endCursor
      hasNextPage
      # hasPreviousPage
    }
  }
}
