query GetUserProfile($username: String, $id: String) {
  user(where: { username: $username, id: $id }) {
    id
    name
    username
    avatar {
      id
      secureUrl
      resourceType
    }
    bio
    _count {
      followers
      following
      posts
    }
    campusProfile {
      department {
        name
        code
      }
      faculty {
        name
      }
      level
    }
  }
}
